name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop

      - name: Security audit dependencies
        run: bin/bundler-audit --update

      - name: Security audit application code
        run: bin/brakeman -q -m2

      - name: Lint Ruby files
        run: bin/rubocop --parallel
  
